In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

# Shape of Array

In [5]:
a.shape

(6,)

# Length of array

In [6]:
len(a)

6

# No. of Dimensions of Array

In [8]:
a.ndim

1

# Type of array

In [9]:
a.dtype

dtype('int32')

# Array of zeroes

In [3]:
import numpy as np
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Array of ones

In [7]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

# Arrange an array

In [11]:
np.arange(10,45,6)

array([10, 16, 22, 28, 34, 40])

# Identity Matrix

In [13]:
np.eye(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

# Arithmetic Operations 

In [14]:
arr1=np.array([[2,5,8],[-3,9,5]])
arr1

array([[ 2,  4,  8],
       [-3,  9,  5]])

### Product 

In [27]:
arr1=np.array([[2,5,8],[-3,9,5]])
arr1*arr1

array([[ 4, 25, 64],
       [ 9, 81, 25]])

### Subtraction

In [22]:
arr1=np.array([[2,5,8],[-3,9,5]])
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

### Addition

In [25]:
arr1=np.array([[2,5,8],[-3,9,5]])
arr2=np.array([[1,-7,5],[0,4,3]])
arr1+arr2

array([[ 3, -2, 13],
       [-3, 13,  8]])

### Exponential

In [26]:
arr1=np.array([[2,5,8],[-3,9,5]])
arr1**2

array([[ 4, 25, 64],
       [ 9, 81, 25]])

### Comparison (i)

In [28]:
arr1=np.array([[2,5,8],[-3,9,5]])
arr2=np.array([[1,-7,5],[0,4,3]])
arr2>arr1

array([[False, False, False],
       [ True, False, False]])

### Comparison (ii)

In [1]:
import numpy as np
arr1=np.array([[2,5,8],[-3,9,5]])
arr2=np.array([[1,5,5],[-3,4,3]])
arr2==arr1

array([[False,  True, False],
       [ True, False, False]])

# Indexing and Slicing

In [7]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr1[2:5]=7
arr1

array([1, 2, 7, 7, 7, 6])

In [12]:
arr1=np.array([1,2,3,4,5,6])
arr1[4]=786
arr1

array([  1,   2,   3,   4, 786,   6])

# Aggregate Functions

### Sum

In [3]:
arr1.sum()

26